name: Good First Issue Candidate Template
description: Propose a potential Good First Issue (candidate)
title: "[Good First Issue]:"
labels: ["Good First Issue Candidate"]
assignees: []
body:
  - type: textarea
    id: intro-gfi-candidate
    attributes:
      label: ⚠️ Good First Issue — Candidate
      value: |
        > This issue is not yet a confirmed Good First Issue.
        > It is being evaluated for suitability and may require
        > clarification or refinement before it is ready to be picked up.
        > 
        > Please wait for maintainer confirmation before starting work.
        >
        > Maintainers and reviewers can read more about Good First Issues:
        > docs/maintainers/good_first_issue_guidelines.md

    validations:
      required: false

  - type: textarea
    id: intro
    attributes:
      label: 🆕🐥 First Timers Only
      description: Who is this issue for?
      value: |
        This issue is reserved for people who have never contributed or have made minimal contributions to [Hiero Python SDK](https://hiero.org).
        We know that creating a pull request (PR) is a major barrier for new contributors.
        The goal of this issue and all other issues in [**find a good first issue**](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Ahiero-ledger+archived%3Afalse+label%3A%22good+first+issue%22+) is to help you make your first contribution to the Hiero Python SDK.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > ### 📋 Good First Issue (GFI) Guidelines
        > 
        > **What we generally consider good first issues:**
        >
        > - **Narrow changes or additions to `src` functionality** that use generic Python skills which can be tested by adding to an existing test. For example:
        >   - `__str__` functions
        >   - `__repr__` functions
        >   - Typing fixes, like return type hints or basic type conflicts
        > - **Refactors of existing examples:**
        >   - Separating existing examples into separate functions
        >   - Or, conversely, taking a split example into a monolithic function
        > - **Improvements to documentation** in examples and source code:
        >   - Docstrings: module docstrings, function docstrings
        >   - Inline comments
        >   - Addition or changes to print statements to improve clarity
        > - **Functional improvements to examples:**
        >   - Additional steps that would help to illustrate functionality
        > - **Specific additions to existing unit or integration tests**
        >
        > **What we generally do NOT consider good first issues:**
        >
        > - Creation of new examples
        > - Creation of new unit and integration tests
        > - Changes to DLT functionality, like `to_proto` and `from_proto`
        > - Anything requiring knowledge of multiple areas of the codebase
        >
        > 📖 *For a more detailed explanation, refer to:  
        > [`docs/maintainers/good_first_issue_candidate_guidelines.md`](docs/maintainers/good_first_issue_candidate_guidelines.md).*

  - type: textarea
    id: issue
    attributes:
      label: 👾 Description of the issue
      description: |
        DESCRIBE THE ISSUE IN A WAY THAT IS UNDERSTANDABLE TO NEW CONTRIBUTORS.
        YOU MUST NOT ASSUME THAT SUCH CONTRIBUTORS HAVE ANY KNOWLEDGE ABOUT THE CODEBASE OR HIERO.
        IT IS HELPFUL TO ADD LINKS TO THE RELEVANT DOCUMENTATION AND/OR CODE SECTIONS.
        BELOW IS AN EXAMPLE.
      value: |
        Edit here. Example provided below.

    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example for problem (hidden in submission) -->
        ## 👾 Description of the issue - Example

        The example for Token Associate Transaction located at examples/tokens/token_associate_transaction.py can be improved. It correctly illustrates how to associate a token, however, it does so all from one function main()

        As everything is grouped together in main(), it is difficult for a user to understand all the individual steps required to associate a token.

        For example:
        ```python

        def run_demo():
            """Monolithic token association demo."""
            print(f"🚀 Connecting to Hedera {network_name} network!")    
            client = Client(Network(network_name))
            operator_id = AccountId.from_string(os.getenv("OPERATOR_ID", ""))
            operator_key = PrivateKey.from_string(os.getenv("OPERATOR_KEY", ""))
            client.set_operator(operator_id, operator_key)
            print(f"✅ Client ready (operator {operator_id})")

            test_key = PrivateKey.generate_ed25519()
            receipt = (
                AccountCreateTransaction()
                .set_key(test_key.public_key())
                .set_initial_balance(Hbar(1))
                .set_account_memo("Test account for token association demo")
                .freeze_with(client)
                .sign(operator_key)
                .execute(client)
            )
            if receipt.status != ResponseCode.SUCCESS:
                raise Exception(receipt.status)
            account_id = receipt.account_id
            print(f"✅ Created test account {account_id}")

            # Create tokens
            tokens = []
            for i in range(3):
                try:
                    receipt = (
                        TokenCreateTransaction()
                        .set_token_name(f"DemoToken{i}")
                        .set_token_symbol(f"DTK{i}")
                        .set_decimals(2)
                        .set_initial_supply(100_000)
                        .set_treasury_account_id(operator_id)
                        .freeze_with(client)
                        .sign(operator_key)
                        .execute(client)
                    )
                    if receipt.status != ResponseCode.SUCCESS:
                        raise Exception(receipt.status)
                    token_id = receipt.token_id
                    tokens.append(token_id)
                    print(f"✅ Created token {token_id}")
                except Exception as e:
                    print(f"❌ Token creation failed: {e}")
                    sys.exit(1)

            # Associate first token
            try:
                TokenAssociateTransaction().set_account_id(account_id).add_token_id(tokens[0]).freeze_with(client).sign(test_key).execute(client)
                print(f"✅ Token {tokens[0]} associated with account {account_id}")
            except Exception as e:
                print(f"❌ Token association failed: {e}")
                sys.exit(1)
        ```

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: |
        AT THIS SECTION YOU NEED TO DESCRIBE THE STEPS NEEDED TO SOLVE THE ISSUE.
        PLEASE BREAK DOWN THE STEPS AS MUCH AS POSSIBLE AND MAKE SURE THAT THEY
        ARE EASY TO FOLLOW. IF POSSIBLE, ADD LINKS TO THE RELEVANT
        DOCUMENTATION AND/OR CODE SECTIONS.
      value: |
        Edit here. Example provided below.

    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example for the solution (hidden in submission) -->
        ## 💡 Solution - Example

        For the TokenAssociateTransaction example, the solution is to split the monolithic main() function for illustrating TokenAssociateTransaction into separate smaller functions which are called from main().
        Such as:
        - Setting up the client
        - Creating an account
        - Creating a token
        - Associating the account to the token

  - type: textarea
    id: implementation
    attributes:
      label: 👩‍💻 Implementation Steps
      description: |
        AT THIS SECTION YOU NEED TO DESCRIBE THE TECHNICAL STEPS NEEDED TO SOLVE THE ISSUE.
        PLEASE BREAK DOWN THE STEPS AS MUCH AS POSSIBLE AND MAKE SURE THAT THEY ARE EASY TO FOLLOW.
        IF POSSIBLE, ADD LINKS TO THE RELEVANT DOCUMENTATION AND/OR CODE.
      value: |
        Edit here. Example provided below.

    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example implementation (hidden in submission) -->
        ### 👩‍💻 Implementation - Example

        To break down the monolithic main function, you need to:
        - [ ] Extract the Key Steps (set up a client, create a test account, create a token, associate the token)
        - [ ] Copy and paste the functionality for each key step into its own function
        - [ ] Pass to each function the variables you need to run it
        - [ ] Call each function in main()
        - [ ] Ensure you return the values you'll need to pass on to the next step in main
        - [ ] Ensure the example still runs and has the same output!

        For example:
        ```python

        def setup_client():
            """Initialize and set up the client with operator account."""

        def create_test_account(client, operator_key):
            """Create a new test account for demonstration."""

        def create_fungible_token(client, operator_id, operator_key):
            """Create a fungible token for association with test account."""

        def associate_token_with_account(client, token_id, account_id, account_key):
            """Associate the token with the test account."""

        def main():
            client, operator_id, operator_key = setup_client()
            account_id, account_private_key = create_test_account(client, operator_key)
            token_id = create_fungible_token(client, operator_id, operator_key)
            associate_token_with_account(client, token_id, account_id, account_private_key)
        ```

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: |
        EDIT OR EXPAND THE CHECKLIST ON WHAT IS REQUIRED TO BE ABLE TO MERGE A PULL REQUEST FOR THIS ISSUE
      value: |
        To be able to merge a pull request for this issue, we need:
        - [ ] **Changelog Entry:** Correct changelog entry (please link to the documentation - [see guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/changelog_entry.md))
        - [ ] **Signed commits:** commits must be DCO and GPG key signed ([see guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/signing.md))
        - [ ] **All Tests Pass:** our workflow checks like unit and integration tests must pass
        - [ ] **Issue is Solved:** The implementation fully addresses the issue requirements as described above
        - [ ] **No Further Changes are Made:** Code review feedback has been addressed and no further changes are requested
    validations:
      required: true

  - type: textarea
    id: contribution_steps
    attributes:
      label: 📋 Step-by-Step Contribution Guide
      description: Provide a contribution workflow suitable for new contributors
      value: |
        If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow.

        - [ ] **Claim this issue:** Comment below that you are interested in working on the issue. Without assignment, your pull requests might be closed and the issue given to another developer.
        - [ ] **Wait for assignment:** A community member with the given rights will add you as an assignee of the issue
        - [ ] **Fork, Branch and Work on the issue:** Create a copy of the repository, create a branch for the issue and solve the problem. For instructions, please read our [Contributing guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/CONTRIBUTING.md) file. Further help can be found at [Set-up Training](https://github.com/hiero-ledger/hiero-sdk-python/tree/main/docs/sdk_developers/training/setup) and [Workflow Training](https://github.com/hiero-ledger/hiero-sdk-python/tree/main/docs/sdk_developers/training/workflow).
        - [ ] **DCO and GPG key sign each commit :** each commit must be -s and -S signed. An explanation on how to do this is at [Signing Guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/signing.md)
        - [ ] **Add a Changelog Entry :** your pull request will require a changelog. Read [Changelog Entry Guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/changelog_entry.md) to learn how.
        - [ ] **Push and Create a Pull Request :** Once your issue is resolved, and your commits are signed, and you have a changelog entry, push your changes and create a pull request. Detailed instructions can be found at [Submit PR Training](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/training/workflow/11_submit_pull_request.md), part of [Workflow Training](https://github.com/hiero-ledger/hiero-sdk-python/tree/main/docs/sdk_developers/training/workflow).
        - [ ] **You did it 🎉:** A maintainer or committer will review your pull request and provide feedback. If approved, we will merge the fix in the main branch. Thanks for being part of the Hiero community as an open-source contributor ❤️

        ***IMPORTANT*** Your pull request CANNOT BE MERGED until you add a changelog entry AND sign your commits each with `git commit -S -s -m "chore: your commit message"` with a GPG key setup.
    validations:
      required: true

  - type: textarea
    id: information
    attributes:
      label: 🤔 Additional Information
      description: Provide any extra resources or context for contributors to solve this good first issue
      value: |
        For more help, we have extensive documentation attributes:
        - [SDK Developer Docs](https://github.com/hiero-ledger/hiero-sdk-python/tree/main/docs/sdk_developers)
        - [SDK Developer Training](https://github.com/hiero-ledger/hiero-sdk-python/tree/main/docs/sdk_developers/training)

        Additionally, we invite you to join our community on our [Discord](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/discord.md) server.

        We also invite you to attend each Wednesday, 2pm UTC our [Python SDK Office Hour and Community Calls](https://zoom-lfx.platform.linuxfoundation.org/meetings/hiero?view=week). The Python SDK Office hour is for hands-on-help and the Community Call for general community discussion.

        You can also ask for help in a comment below!
