name: Beginner Issue Template
description: Create a Beginner Issue for fairly new contributors
title: "[Beginner]: "
labels: ["beginner"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ---
        ## **Thanks for contributing!** 😊

        We truly appreciate your time and effort. If this is your first open-source contribution, welcome!
        This template is designed to help you create a Beginner-friendly issue: an easy, well-scoped task that helps fairly new contributors learn the codebase and build their skills.
        ---
  - type: textarea
    id: intro
    attributes:
      label: 🐥 Beginner Friendly
      description: Who is this issue for?
      value: |
        This issue is intended for contributors who have previously completed a Good First Issue in [Hiero](https://hiero.org) and are at a beginner level.
        We recognize that gaining confidence and building skills are equally important steps in the open-source contributor journey.
        The purpose of this issue—and others listed under [**Find a beginner issue**](https://github.com/hiero-ledger/hiero-sdk-python/issues?q=is%3Aissue%20state%3Aopen%20label%3Abeginner%20no%3Aassignee)—is to provide a supportive, low-pressure environment where you can learn, practice, and grow your contribution skills with confidence.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > ### 🐥 Beginner Issue Guidelines
        >
        > Beginner Issues are intended for contributors who are familiar with the project workflow and have **some programming experience** and are wanting opportunities to build skills.
        > These issues may require **light investigation, interpretation of existing code, and some self-initiative**, but should remain **well-scoped with a clear intent**.
        >
        > **What we generally consider beginner issues:**
        >
        > - **Small, well-scoped updates to existing tests**:
        >   - Adjusting or extending an existing test to cover a simple case
        > - **Narrow changes or additions to `src` functionality** using common Python skills, such as:
        >   - Implementing or refining `__str__` methods
        >   - Implementing or refining `__repr__` methods
        >   - Typing improvements, such as return type hints or basic type conflicts
        > - **Documentation improvements** in examples such as creating new examples or docstrings for existing functions
        > - **Functional improvements to existing examples**:
        >   - Adding steps or variations to better demonstrate functionality
        >
        > **What we generally do NOT consider beginner issues:**
        > - Tasks better suited for Good First Issues (purely mechanical or fully guided changes)
        > - Creating entirely new examples or test suites
        > - Changes to core DLT functionality (for example, `to_proto` or `from_proto`)
        > - Work that requires deep knowledge across multiple areas of the codebase

        > 📖 *For a more detailed explanation, refer to:  
        > [`docs/maintainers/beginner_issue_guidelines.md`](docs/maintainers/beginner_issue_guidelines.md).*

  - type: textarea
    id: issue
    attributes:
      label: 👾 Description of the issue
      description: |
        DESCRIBE THE ISSUE IN A WAY THAT IS UNDERSTANDABLE AND APPROACHABLE TO BEGINNER CONTRIBUTORS.
        ASSUME SUCH CONTRIBUTORS HAVE AT MOST BEGINNER-LEVEL KNOWLEDGE ABOUT PROGRAMMING, THE CODEBASE AND HIERO.
        IT IS HELPFUL TO ADD LINKS TO THE RELEVANT DOCUMENTATION AND/OR CODE SECTIONS.
        SLIGHTLY CHALLENGE THEM TO ENCOURAGE LEARNING AND RESEARCH BUT MAKE SURE THE ISSUE IS STILL SIMPLE.
        BELOW IS AN EXAMPLE.
      value: |
        Edit here. Example provided below.

    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example for problem (hidden in submission) -->
        ## 👾 Description of the issue - Example

        The `AccountId` class at src/hiero_sdk_python/account/account_id.py implements a `__repr__()` method which currently falls back to the default object representation, which is less helpful
        when debugging.

        For example, printing an `AccountId` instance in a REPL currently produces output similar to:

        ```python
        <hiero.account_id.AccountId object at 0x7f9c2a3b8d60>
        ```

        This makes it difficult to quickly identify the actual account ID value during debugging sessions.

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: |
        AT THIS SECTION YOU NEED TO DESCRIBE THE STEPS NEEDED TO SOLVE THE ISSUE.
        PLEASE BREAK DOWN THE STEPS AS MUCH AS POSSIBLE AND MAKE SURE THAT THEY
        ARE EASY TO FOLLOW. IF POSSIBLE, ADD LINKS TO THE RELEVANT
        DOCUMENTATION AND/OR CODE SECTIONS.
      value: |
        Edit here. Example provided below.

    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example for the solution (hidden in submission) -->
        To improve this, we want to implement a more informative `__repr__()` method for the `AccountId` class that clearly displays the account ID in a recognizable format.

        After this improvement, `repr(account_id)` should return a clear and descriptive value that reflects
        the account’s shard, realm, and number. For example:

        ```python
        AccountId(shard=0, realm=0, num=1234)
        ```

  - type: textarea
    id: implementation
    attributes:
      label: 👩‍💻 Implementation Steps
      description: |
        AT THIS SECTION YOU NEED TO DESCRIBE THE TECHNICAL STEPS NEEDED TO SOLVE THE ISSUE.
        PLEASE BREAK DOWN THE STEPS AS MUCH AS POSSIBLE AND MAKE SURE THAT THEY ARE EASY TO FOLLOW.
        IF POSSIBLE, ADD LINKS TO THE RELEVANT DOCUMENTATION AND/OR CODE.
      value: |
        Edit here. Example provided below.

    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example implementation (hidden in submission) -->
        ### 👩‍💻 Implementation - Example

        To implement this change, beginner contributors should:

        - [ ] Locate the `AccountId` class in the `src/` directory
        - [ ] Review the existing `__str__()` method to understand how account IDs are currently formatted
        - [ ] Review the `__init__()` method to see which fields (`shard`, `realm`, `num`, `alias_key`) define an account
        - [ ] Check whether other ID classes in the SDK implement `__repr__()` and follow a similar pattern
        - [ ] Implement or refine the `__repr__()` method so it:
          - Clearly displays `shard`, `realm`, and `num` values
          - Includes `alias_key` when the account is created using an alias
          - Uses keyword-style formatting for readability
        - [ ] Test the new `__repr__()` method expanding the unit test for AccountId

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: |
        EDIT OR EXPAND THE CHECKLIST ON WHAT IS REQUIRED TO BE ABLE TO MERGE A PULL REQUEST FOR THIS ISSUE
      value: |
        To be able to merge a pull request for this issue, we need:
        - [ ] **Assignment:** You must be assigned to the issue, comment: `/assign` in the issue to get assigned [see guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/training/workflow/04_assigning_issues.md)
        - [ ] **Changelog Entry:** Correct changelog entry [see guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/changelog_entry.md)
        - [ ] **Signed commits:** commits must be DCO and GPG key signed as `git commit -S -s -m "chore: my change"` with a GPG key set up [see guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/signing.md)
        - [ ] **All Tests Pass:** our workflow checks like unit and integration tests must pass
        - [ ] **Issue is Solved:** The implementation fully addresses the issue requirements as described above
        - [ ] **No Further Changes are Made:** Code review feedback has been addressed and no further changes are requested
    validations:
      required: true

  - type: textarea
    id: contribution_steps
    attributes:
      label: 📋 Step-by-Step Contribution Guide
      description: Provide a contribution workflow suitable for new contributors
      value: |
        - [ ] **Assignment:** You must be assigned to the issue, comment: `/assign` in the issue to get assigned [see guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/training/workflow/04_assigning_issues.md)
        - [ ] **Fork, Branch and Work on the issue:** Create a copy of the repository, create a branch for the issue and solve the problem. For instructions, please read our [Contributing guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/CONTRIBUTING.md) file. Further help can be found at [Set-up Training](https://github.com/hiero-ledger/hiero-sdk-python/tree/main/docs/sdk_developers/training/setup) and [Workflow Training](https://github.com/hiero-ledger/hiero-sdk-python/tree/main/docs/sdk_developers/training/workflow).
        - [ ] **DCO and GPG key sign each commit :** each commit must be -s and -S signed. An explanation on how to do this is at [Signing Guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/signing.md)
        - [ ] **Add a Changelog Entry :** your pull request will require a changelog. Read [Changelog Entry Guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/changelog_entry.md) to learn how.
        - [ ] **Push and Create a Pull Request :** Once your issue is resolved, and your commits are signed, and you have a changelog entry, push your changes and create a pull request. Detailed instructions can be found at [Submit PR Training](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/training/workflow/11_submit_pull_request.md), part of [Workflow Training](https://github.com/hiero-ledger/hiero-sdk-python/tree/main/docs/sdk_developers/training/workflow).
        - [ ] **You did it 🎉:** A maintainer or committer will review your pull request and provide feedback. If approved, we will merge the fix in the main branch. Thanks for being part of the Hiero community as an open-source contributor ❤️

        ***IMPORTANT*** You will ONLY be assigned to the issue if you comment: `/assign`
        ***IMPORTANT*** Your pull request CANNOT BE MERGED until you add a changelog entry AND sign your commits each with `git commit -S -s -m "chore: your commit message"` with a GPG key setup.
    validations:
      required: true

  - type: textarea
    id: ai_usage_guidelines
    attributes:
      label: 🤖 AI Usage Guidelines
      description: Guidance on using AI tools responsibly for this issue
      value: |
        You are welcome to use AI to help you understand and solve this issue.

        Because AI tools can sometimes make mistakes, please take care to:

        - Only implement what is described in this issue  
        - Avoid changing anything else in the file  
        - Be careful when modifying parameters or return statements, as this may affect runtime behavior  

        If you're unsure, ask your mentor or the maintainers for help — they can provide expert Python SDK guidance and point you to the right examples or methods.
    validations:
      required: false

  - type: textarea
    id: information
    attributes:
      label: 🤔 Additional Information
      description: Provide any extra resources or context for contributors to solve this beginner issue
      value: |
        For more help, we have extensive documentation:
        - [SDK Developer Docs](https://github.com/hiero-ledger/hiero-sdk-python/tree/main/docs/sdk_developers)
        - [SDK Developer Training](https://github.com/hiero-ledger/hiero-sdk-python/tree/main/docs/sdk_developers/training)

        Additionally, we invite you to join our community on our [Discord](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/discord.md) server.

        We also invite you to attend each Wednesday, 2pm UTC our [Python SDK Office Hour and Community Calls](https://zoom-lfx.platform.linuxfoundation.org/meetings/hiero?view=week). The Python SDK Office hour is for hands-on-help and the Community Call for general community discussion.

        You can also ask for help in a comment below!
