name: Issue Assignment Bot

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  contents: read

concurrency:
  group: assign-issue-${{ github.repository }}
  cancel-in-progress: false

jobs:
  assign-issue:
    runs-on: hl-sdk-py-lin-md
    if: github.event.issue.pull_request == null

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout trusted base repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          ref: ${{ github.event.repository.default_branch }}

      - name: Assign issue
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/scripts/bot-issue-assign-on-comment.js');
            await script({ github, context, core });
